import * as vscode from 'vscode';
import { DiagnosisResult, DiagnosisIssue } from './cli';

export interface DiagnosisReference {
    appId: string;
    branch: string;
    jobId: string;
    status: string;
    timestamp: string;
    issues: DiagnosisIssue[];
    consoleUrl: string;
}

export class DiagnosisShareService {
    
    /**
     * Generate a shareable reference ID for a diagnosis
     */
    static generateReferenceId(result: DiagnosisResult): string {
        return `amplify://${result.appId}/${result.branch}/${result.jobId}`;
    }

    /**
     * Get AWS Console URL for a job
     */
    static getConsoleUrl(appId: string, branch: string, jobId: string, region?: string): string {
        const awsRegion = region || vscode.workspace.getConfiguration('amplifyMonitor').get<string>('defaultRegion') || 'us-east-1';
        return `https://${awsRegion}.console.aws.amazon.com/amplify/home?region=${awsRegion}#/${appId}/${branch}/${jobId}`;
    }

    /**
     * Copy diagnosis as Markdown (for Slack, Teams, GitHub, etc.)
     */
    static async copyAsMarkdown(result: DiagnosisResult): Promise<void> {
        const region = vscode.workspace.getConfiguration('amplifyMonitor').get<string>('defaultRegion') || 'us-east-1';
        const consoleUrl = this.getConsoleUrl(result.appId, result.branch, result.jobId, region);
        
        let markdown = `## 🔴 Amplify Build Failed\n\n`;
        markdown += `| Property | Value |\n|----------|-------|\n`;
        markdown += `| **App ID** | \`${result.appId}\` |\n`;
        markdown += `| **Branch** | \`${result.branch}\` |\n`;
        markdown += `| **Job ID** | \`${result.jobId}\` |\n`;
        markdown += `| **Status** | ${result.status} |\n`;
        markdown += `| **Console** | [View in AWS Console](${consoleUrl}) |\n\n`;

        if (result.issues.length > 0) {
            markdown += `### Issues Found (${result.issues.length})\n\n`;
            
            for (const issue of result.issues) {
                markdown += `#### ⚠️ ${issue.pattern.replace(/_/g, ' ')}\n\n`;
                markdown += `**Root Cause:** ${issue.rootCause}\n\n`;
                
                if (issue.suggestedFixes.length > 0) {
                    markdown += `**Suggested Fixes:**\n`;
                    for (const fix of issue.suggestedFixes) {
                        markdown += `- ${fix}\n`;
                    }
                    markdown += '\n';
                }
            }
        } else {
            markdown += `### ✅ No specific issues detected\n\n`;
            markdown += `Check the [build logs](${consoleUrl}) for more details.\n`;
        }

        markdown += `\n---\n*Generated by [Amplify Monitor](https://marketplace.visualstudio.com/items?itemName=SagaraHarasgama.amplify-monitor)*`;

        await vscode.env.clipboard.writeText(markdown);
        vscode.window.showInformationMessage('Diagnosis copied to clipboard as Markdown!');
    }

    /**
     * Copy diagnosis as plain text
     */
    static async copyAsText(result: DiagnosisResult): Promise<void> {
        const region = vscode.workspace.getConfiguration('amplifyMonitor').get<string>('defaultRegion') || 'us-east-1';
        const consoleUrl = this.getConsoleUrl(result.appId, result.branch, result.jobId, region);
        
        let text = `AMPLIFY BUILD FAILED\n`;
        text += `${'='.repeat(50)}\n\n`;
        text += `App ID:  ${result.appId}\n`;
        text += `Branch:  ${result.branch}\n`;
        text += `Job ID:  ${result.jobId}\n`;
        text += `Status:  ${result.status}\n`;
        text += `Console: ${consoleUrl}\n\n`;

        if (result.issues.length > 0) {
            text += `ISSUES FOUND (${result.issues.length})\n`;
            text += `${'-'.repeat(50)}\n\n`;
            
            for (let i = 0; i < result.issues.length; i++) {
                const issue = result.issues[i];
                text += `${i + 1}. ${issue.pattern.replace(/_/g, ' ')}\n`;
                text += `   Root Cause: ${issue.rootCause}\n`;
                
                if (issue.suggestedFixes.length > 0) {
                    text += `   Fixes:\n`;
                    for (const fix of issue.suggestedFixes) {
                        text += `   - ${fix}\n`;
                    }
                }
                text += '\n';
            }
        }

        await vscode.env.clipboard.writeText(text);
        vscode.window.showInformationMessage('Diagnosis copied to clipboard as text!');
    }

    /**
     * Generate GitHub issue template
     */
    static async copyAsGitHubIssue(result: DiagnosisResult): Promise<void> {
        const region = vscode.workspace.getConfiguration('amplifyMonitor').get<string>('defaultRegion') || 'us-east-1';
        const consoleUrl = this.getConsoleUrl(result.appId, result.branch, result.jobId, region);
        
        let issue = `## Build Failure: Job #${result.jobId}\n\n`;
        issue += `### Build Information\n\n`;
        issue += `- **Branch:** \`${result.branch}\`\n`;
        issue += `- **Job ID:** \`${result.jobId}\`\n`;
        issue += `- **Status:** ${result.status}\n`;
        issue += `- **AWS Console:** [View Build](${consoleUrl})\n\n`;

        issue += `### Detected Issues\n\n`;
        
        if (result.issues.length > 0) {
            for (const iss of result.issues) {
                issue += `#### ${iss.pattern.replace(/_/g, ' ')}\n\n`;
                issue += `> ${iss.rootCause}\n\n`;
                
                if (iss.suggestedFixes.length > 0) {
                    issue += `**Suggested Fixes:**\n`;
                    for (const fix of iss.suggestedFixes) {
                        issue += `- [ ] ${fix}\n`;
                    }
                    issue += '\n';
                }
            }
        } else {
            issue += `No specific issues detected. Manual investigation required.\n\n`;
        }

        issue += `### Steps to Reproduce\n\n`;
        issue += `1. Push to \`${result.branch}\` branch\n`;
        issue += `2. Build triggers automatically\n`;
        issue += `3. Build fails with above error(s)\n\n`;

        issue += `### Expected Behavior\n\n`;
        issue += `Build should complete successfully.\n\n`;

        issue += `### Additional Context\n\n`;
        issue += `<!-- Add any other context, screenshots, or logs here -->\n\n`;

        issue += `---\n`;
        issue += `*Generated by Amplify Monitor VS Code Extension*`;

        await vscode.env.clipboard.writeText(issue);
        vscode.window.showInformationMessage('GitHub issue template copied to clipboard!');
    }

    /**
     * Copy just the reference link
     */
    static async copyReferenceLink(result: DiagnosisResult): Promise<void> {
        const region = vscode.workspace.getConfiguration('amplifyMonitor').get<string>('defaultRegion') || 'us-east-1';
        const consoleUrl = this.getConsoleUrl(result.appId, result.branch, result.jobId, region);
        
        await vscode.env.clipboard.writeText(consoleUrl);
        vscode.window.showInformationMessage('AWS Console link copied to clipboard!');
    }

    /**
     * Copy a short summary (for quick sharing in chat)
     */
    static async copyShortSummary(result: DiagnosisResult): Promise<void> {
        const issueCount = result.issues.length;
        const mainIssue = issueCount > 0 ? result.issues[0].pattern.replace(/_/g, ' ') : 'Unknown';
        const region = vscode.workspace.getConfiguration('amplifyMonitor').get<string>('defaultRegion') || 'us-east-1';
        const consoleUrl = this.getConsoleUrl(result.appId, result.branch, result.jobId, region);

        let summary = `🔴 Build #${result.jobId} failed on \`${result.branch}\``;
        if (issueCount > 0) {
            summary += ` - ${mainIssue}`;
            if (issueCount > 1) {
                summary += ` (+${issueCount - 1} more)`;
            }
        }
        summary += `\n${consoleUrl}`;

        await vscode.env.clipboard.writeText(summary);
        vscode.window.showInformationMessage('Short summary copied to clipboard!');
    }

    /**
     * Show share options in quick pick
     */
    static async showShareOptions(result: DiagnosisResult): Promise<void> {
        const options = [
            {
                label: '$(markdown) Copy as Markdown',
                description: 'For Slack, Teams, GitHub comments',
                action: () => this.copyAsMarkdown(result)
            },
            {
                label: '$(github) Copy as GitHub Issue',
                description: 'Issue template with checkboxes',
                action: () => this.copyAsGitHubIssue(result)
            },
            {
                label: '$(comment) Copy Short Summary',
                description: 'Quick summary for chat',
                action: () => this.copyShortSummary(result)
            },
            {
                label: '$(file-text) Copy as Plain Text',
                description: 'Simple text format',
                action: () => this.copyAsText(result)
            },
            {
                label: '$(link-external) Copy Console Link',
                description: 'AWS Console URL',
                action: () => this.copyReferenceLink(result)
            },
            {
                label: '$(globe) Open in AWS Console',
                description: 'View build in browser',
                action: () => {
                    const region = vscode.workspace.getConfiguration('amplifyMonitor').get<string>('defaultRegion') || 'us-east-1';
                    const url = this.getConsoleUrl(result.appId, result.branch, result.jobId, region);
                    vscode.env.openExternal(vscode.Uri.parse(url));
                }
            }
        ];

        const selected = await vscode.window.showQuickPick(options, {
            placeHolder: `Share diagnosis for Job #${result.jobId}`,
            title: 'Share Build Diagnosis'
        });

        if (selected) {
            await selected.action();
        }
    }

    /**
     * Create a mention string for inline use
     */
    static getMentionString(result: DiagnosisResult): string {
        return `[Build #${result.jobId}](${this.getConsoleUrl(result.appId, result.branch, result.jobId)})`;
    }

    /**
     * Export diagnosis to JSON file
     */
    static async exportToFile(result: DiagnosisResult): Promise<void> {
        const region = vscode.workspace.getConfiguration('amplifyMonitor').get<string>('defaultRegion') || 'us-east-1';
        
        const reference: DiagnosisReference = {
            appId: result.appId,
            branch: result.branch,
            jobId: result.jobId,
            status: result.status,
            timestamp: new Date().toISOString(),
            issues: result.issues,
            consoleUrl: this.getConsoleUrl(result.appId, result.branch, result.jobId, region)
        };

        const uri = await vscode.window.showSaveDialog({
            defaultUri: vscode.Uri.file(`amplify-diagnosis-${result.jobId}.json`),
            filters: {
                'JSON': ['json'],
                'Markdown': ['md']
            }
        });

        if (uri) {
            const fs = require('fs');
            const content = uri.fsPath.endsWith('.md') 
                ? await this.generateMarkdownContent(result)
                : JSON.stringify(reference, null, 2);
            
            fs.writeFileSync(uri.fsPath, content);
            
            const doc = await vscode.workspace.openTextDocument(uri);
            await vscode.window.showTextDocument(doc);
            vscode.window.showInformationMessage(`Diagnosis exported to ${uri.fsPath}`);
        }
    }

    private static async generateMarkdownContent(result: DiagnosisResult): Promise<string> {
        const region = vscode.workspace.getConfiguration('amplifyMonitor').get<string>('defaultRegion') || 'us-east-1';
        const consoleUrl = this.getConsoleUrl(result.appId, result.branch, result.jobId, region);
        
        let md = `# Amplify Build Diagnosis Report\n\n`;
        md += `**Generated:** ${new Date().toLocaleString()}\n\n`;
        md += `## Build Information\n\n`;
        md += `| Property | Value |\n|----------|-------|\n`;
        md += `| App ID | \`${result.appId}\` |\n`;
        md += `| Branch | \`${result.branch}\` |\n`;
        md += `| Job ID | \`${result.jobId}\` |\n`;
        md += `| Status | **${result.status}** |\n`;
        md += `| Console | [Open in AWS](${consoleUrl}) |\n\n`;

        md += `## Detected Issues\n\n`;
        
        if (result.issues.length === 0) {
            md += `✅ No specific issues detected.\n\n`;
        } else {
            for (let i = 0; i < result.issues.length; i++) {
                const issue = result.issues[i];
                md += `### ${i + 1}. ${issue.pattern.replace(/_/g, ' ')}\n\n`;
                md += `**Root Cause:** ${issue.rootCause}\n\n`;
                
                if (issue.suggestedFixes.length > 0) {
                    md += `**Suggested Fixes:**\n\n`;
                    for (const fix of issue.suggestedFixes) {
                        md += `- ${fix}\n`;
                    }
                    md += '\n';
                }
            }
        }

        md += `---\n\n`;
        md += `*Report generated by [Amplify Monitor](https://marketplace.visualstudio.com/items?itemName=SagaraHarasgama.amplify-monitor)*\n`;

        return md;
    }
}
